# Generated by Django 5.0.4 on 2024-04-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlogin',
            name='phone',
            field=models.IntegerField(max_length=12),
        ),
    ]
