# Generated by Django 5.0.4 on 2024-04-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_adminlogin_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlogin',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
