# Generated by Django 5.0.4 on 2024-04-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_createcontest'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('conpass', models.CharField(max_length=20)),
            ],
        ),
    ]
